stages:
  data:
    cmd: python src/main.py --stage data --csv data/raw/bike_sharing_modified.csv --target cnt
    deps:
      - src/main.py
      - src/data.py
      - data/raw
    outs:
      - data/processed

  train:
    cmd: python src/main.py --stage train
    deps:
      - src/main.py
      - src/train_predict.py
      - data/processed/bike_sharing_cleaned_train.csv
    outs:
      - models
    metrics:
      - metrics/train

  evaluate:
    cmd: python src/main.py --stage evaluate
    deps:
      - src/main.py
      - src/train_predict.py
      - data/processed/bike_sharing_cleaned_test.csv
      - models
    metrics:
      - metrics/eval

  visualize:
    cmd: python src/main.py --stage visualize
    deps:
      - src/main.py
      - src/visualize.py
      - metrics
    outs:
      - reports

